create database UNIVERSITY_SYSTEM
USE UNIVERSITY_SYSTEM

CREATE TABLE DEPARTMENTS (
	DepartmentID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE LECTORS (
	LectorID INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) NOT NULL,
    DepartmentID INT NOT NULL,
	FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENTS(DepartmentID)
);

CREATE TABLE COURSES (
	CourseID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    LectorID INT NOT NULL,
    FOREIGN KEY (LectorID) REFERENCES LECTORS(LectorID)
);

CREATE TABLE STUDENTS (
    StudentID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    DepartmentID INT NOT NULL,
    FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENTS(DepartmentID)
);

CREATE TABLE LECTORS_INFO (
	LectorID INT PRIMARY KEY AUTO_INCREMENT,
	Email VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL,
	Adress VARCHAR(100) NOT NULL,
	FOREIGN KEY (LectorID) REFERENCES LECTORS(LectorID)
);

CREATE TABLE STUDENT_COURSE (
	StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    PRIMARY KEY (StudentID, CourseId),
    FOREIGN KEY (StudentID) REFERENCES STUDENTS(StudentID),
    FOREIGN KEY (CourseID) REFERENCES COURSES(CourseID)
);

DROP DATABASE UNIVERSITY_SYSTEM

